name: Continuous Deployment

on:
    push:
        branches: [main]

jobs:
    continuous-integration:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "15"
            - name: install dependencies
              run: npm i
            - name: test
              run: npm test
    continuous-deployment:
        needs: [continuous-integration]
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "15"
            - name: change target environment
              run: |
                  sed -i 's/^REACT_APP_TARGET_ENV=LOCAL$/REACT_APP_TARGET_ENV=PROD/g' .env
            - name: download AWS CLI
              run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            - name: install AWS CLI
              run: unzip "awscliv2.zip" && sudo ./aws/install --update
            - name: install dependencies
              run: npm i
            - name: build
              run: npm build && cp .env ./build
            - name: deploy
              run: aws s3 sync ./build/ ${{ secrets.AWS_BUCKET_PATH }}
            - name: invalidate cache
              run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_DISTRIBUTION_ID }} --paths "/*"
