name: Continuous Integration

on:
  push:
    branches:
      - "*"
      - "!main"
  pull_request:
    branches: 
      - "*"

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: install dependencies
        run: npm i
      - name: test
        run: npm test