name: Production

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: test
        run: cd ./capstone-client && npm test
      - name: download AWS CLI
        run: cd ../ && curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - name: install AWS CLI
        run: unzip "awscliv2.zip" && ./aws/install
      - name: build
        run: cd ./capstone-client && npm build
      - name: release
        run: aws s3 sync ./build/ $S3_BUCKET_PATH
      - name: invalidate cache
        run: aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
